name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    uses: centralnicgroup-opensource/rtldev-middleware-shareable-workflows/.github/workflows/gulp-release-notification-plugin-release.yml@main
    secrets: inherit