name: Test Workflow

on:
  push:
    branches:
      - main

jobs:
  extract-pr-info:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: run build
      run: |
        echo "GITHUB_SHA is ${{ github.sha }}"
        echo "GITHUB_REF is ${{ github.ref }}"
        echo "${{ github.event.ref }} - ${{ github.event.ref_type }}"
